import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  GENERATED_AGENT_MARKER,
  GENERATED_AGENT_MARKER_LEGACY,
  GENERATED_AGENT_PREFIX,
  isOwnedAgentFile,
} from "../../../extensions/pi-claude-marketplace/bridges/agents/marker.ts";

test("exports the exact generated agent prefix", () => {
  // arrange
  const expectedPrefix = "pi-claude-marketplace-";

  // act
  const prefix = GENERATED_AGENT_PREFIX;

  // assert
  assert.strictEqual(prefix, expectedPrefix);
});

test("exports the exact current ownership marker", () => {
  // arrange
  const expectedMarker = "generatedBy: pi-claude-marketplace";

  // act
  const marker = GENERATED_AGENT_MARKER;

  // assert
  assert.strictEqual(marker, expectedMarker);
});

test("exports the exact legacy ownership marker", () => {
  // arrange
  const expectedMarker = "generated by pi-claude-marketplace";

  // act
  const marker = GENERATED_AGENT_MARKER_LEGACY;

  // assert
  assert.strictEqual(marker, expectedMarker);
});

test("accepts a missing target with an owned basename", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-missing-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-missing.md");
  const expectedOwnership = { ok: true };

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.deepStrictEqual(await readdir(directory), []);
});

test("rejects a foreign basename before reading its missing target", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-basename-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "foreign-agent.md");
  const expectedOwnership = {
    ok: false,
    reason: 'target filename "foreign-agent.md" does not start with "pi-claude-marketplace-"',
  };

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.deepStrictEqual(await readdir(directory), []);
});

test("accepts a file with the current ownership marker", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-current-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-current.md");
  const agentBytes = `---
name: pi-claude-marketplace-current
provenance:
  generatedBy: pi-claude-marketplace
---

Current agent body.
`;
  const expectedOwnership = { ok: true };
  await writeFile(targetPath, agentBytes);

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.strictEqual(await readFile(targetPath, "utf8"), agentBytes);
});

test("accepts a file with only the legacy ownership marker", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-legacy-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-legacy.md");
  const agentBytes = `---
name: pi-claude-marketplace-legacy
---

<!--
generated by pi-claude-marketplace
-->

Legacy agent body.
`;
  const expectedOwnership = { ok: true };
  await writeFile(targetPath, agentBytes);

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.strictEqual(await readFile(targetPath, "utf8"), agentBytes);
});

test("rejects a marker-free file with an owned basename", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-foreign-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-foreign.md");
  const agentBytes = `---
name: foreign-agent
description: Developer-owned content
---

Foreign agent body.
`;
  const expectedOwnership = {
    ok: false,
    reason: `target ${targetPath} is missing the generated marker`,
  };
  await writeFile(targetPath, agentBytes);

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.strictEqual(await readFile(targetPath, "utf8"), agentBytes);
});

test("rejects a one-byte variant of the current marker", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-near-current-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-near-current.md");
  const agentBytes = `---
name: pi-claude-marketplace-near-current
provenance:
  generatedBy: pi-claude-marketplacE
---

Near-current agent body.
`;
  const expectedOwnership = {
    ok: false,
    reason: `target ${targetPath} is missing the generated marker`,
  };
  await writeFile(targetPath, agentBytes);

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.strictEqual(await readFile(targetPath, "utf8"), agentBytes);
});

test("rejects a one-byte variant of the legacy marker", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-near-legacy-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-near-legacy.md");
  const agentBytes = `---
name: pi-claude-marketplace-near-legacy
---

<!--
generated by pi-claude-marketplacE
-->

Near-legacy agent body.
`;
  const expectedOwnership = {
    ok: false,
    reason: `target ${targetPath} is missing the generated marker`,
  };
  await writeFile(targetPath, agentBytes);

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.strictEqual(await readFile(targetPath, "utf8"), agentBytes);
});

test("rejects malformed bytes without an ownership marker", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-malformed-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-malformed.md");
  const agentBytes = Buffer.from([0xff, 0xfe, 0xfd, 0x00]);
  const expectedOwnership = {
    ok: false,
    reason: `target ${targetPath} is missing the generated marker`,
  };
  await writeFile(targetPath, agentBytes);

  // act
  const ownership = await isOwnedAgentFile(targetPath);

  // assert
  assert.deepStrictEqual(ownership, expectedOwnership);
  assert.deepStrictEqual(await readFile(targetPath), agentBytes);
});

test("propagates a read error for a directory target", async (t) => {
  // arrange
  const directory = await mkdtemp(path.join(tmpdir(), "agent-marker-unreadable-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const targetPath = path.join(directory, "pi-claude-marketplace-directory.md");
  await mkdir(targetPath);

  // act
  const ownershipError: unknown = await isOwnedAgentFile(targetPath).then(
    () => undefined,
    (error: unknown) => error,
  );

  // assert
  assert.ok(ownershipError instanceof Error);
  assert.deepStrictEqual(
    {
      name: ownershipError.name,
      // The errno path is not projected: some runtime majors attach it to an fd-based read
      // failure and earlier ones leave it undefined. Code and syscall are the contract.
      code: (ownershipError as NodeJS.ErrnoException).code,
      syscall: (ownershipError as NodeJS.ErrnoException).syscall,
    },
    {
      name: "Error",
      code: "EISDIR",
      syscall: "read",
    },
  );
  assert.deepStrictEqual(await readdir(targetPath), []);
});
