import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, test, type TestContext } from "node:test";

import {
  abortPreparedAgents,
  commitPreparedAgents,
  prepareStagePluginAgents,
} from "../../../extensions/pi-claude-marketplace/bridges/agents/stage.ts";
import { locationsFor } from "../../../extensions/pi-claude-marketplace/persistence/locations.ts";
import { AgentOwnershipConflictError } from "../../../extensions/pi-claude-marketplace/shared/errors-bridges.ts";

import type { ResolvedPluginInstallable } from "../../../extensions/pi-claude-marketplace/domain/resolver.ts";
import type { AgentsIndex } from "../../../extensions/pi-claude-marketplace/persistence/agents-index-schema.ts";

async function createStageTree(t: TestContext, prefix: string) {
  const scopeRoot = await mkdtemp(path.join(tmpdir(), prefix));
  t.after(() => rm(scopeRoot, { recursive: true, force: true, maxRetries: 3 }));
  const pluginRoot = path.join(scopeRoot, "plugin");
  const agentsSourceDir = path.join(pluginRoot, "agents");
  await mkdir(agentsSourceDir, { recursive: true });
  const locations = locationsFor("project", scopeRoot);
  const pluginDataDir = path.join(locations.dataRoot, "catalog", "acme");
  return { scopeRoot, pluginRoot, agentsSourceDir, locations, pluginDataDir };
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await stat(filePath);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return false;
    }

    throw error;
  }
}

describe("prepareStagePluginAgents", () => {
  test("returns a frozen no-op result when no agents component is declared", async (t) => {
    // arrange
    const { pluginRoot, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-stage-no-component-",
    );
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: [],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: [] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;

    // act
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir: null,
    });

    // assert
    assert.deepStrictEqual(prepared, {
      kind: "noop",
      result: { stagedNames: [], recorded: [], warnings: [], failed: [] },
    });
    assert.strictEqual(Object.isFrozen(prepared.result.stagedNames), true);
    assert.strictEqual(Object.isFrozen(prepared.result.recorded), true);
    assert.strictEqual(Object.isFrozen(prepared.result.warnings), true);
    assert.strictEqual(Object.isFrozen(prepared.result.failed), true);
    assert.strictEqual(await exists(locations.agentsStagingDir), false);
  });

  test("keeps an empty agents directory as a no-op without materializing agent paths", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-stage-empty-",
    );
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;

    // act
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
      knownSkills: [],
    });
    const cleanupLeak = await commitPreparedAgents(prepared);

    // assert
    assert.deepStrictEqual(prepared, {
      kind: "noop",
      result: { stagedNames: [], recorded: [], warnings: [], failed: [] },
    });
    assert.strictEqual(cleanupLeak, undefined);
    assert.strictEqual(await exists(locations.agentsDir), false);
    assert.strictEqual(await exists(locations.agentsIndexPath), false);
  });

  test("stages the complete agent-family records and generated bytes", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-stage-family-",
    );
    const helperSource = `---
name: acme-helper
description: Helper agent
tools: Read,Grep
---

Helper body.
`;
    const botSource = `---
name: bot
description: A bot agent
model: sonnet
tools: Read,Bash,Edit
---

You are a bot. Read from \${CLAUDE_PLUGIN_ROOT}/data and \${CLAUDE_PROJECT_DIR}.
`;
    const helperSourcePath = path.join(agentsSourceDir, "acme-helper.md");
    const botSourcePath = path.join(agentsSourceDir, "bot.md");
    const helperTargetPath = path.join(locations.agentsDir, "pi-claude-marketplace-acme-helper.md");
    const botTargetPath = path.join(locations.agentsDir, "pi-claude-marketplace-acme-bot.md");
    const expectedHelperBytes = `---
name: pi-claude-marketplace-acme-helper
description: Helper agent
tools: read,grep
systemPromptMode: replace
inheritProjectContext: true
inheritSkills: false
provenance:
  generatedBy: pi-claude-marketplace
  sourcePlugin: acme
  sourceAgent: acme-helper
  sourcePath: ${helperSourcePath}
  droppedFields: []
  droppedTools: []
  warnings: []
---

Helper body.
`;
    const expectedBotBytes = `---
name: pi-claude-marketplace-acme-bot
description: A bot agent
model: anthropic/claude-sonnet-4-6
tools: read,bash,edit
systemPromptMode: replace
inheritProjectContext: true
inheritSkills: false
provenance:
  generatedBy: pi-claude-marketplace
  sourcePlugin: acme
  sourceAgent: bot
  sourcePath: ${botSourcePath}
  originalModel: sonnet
  droppedFields: []
  droppedTools: []
  warnings: []
---

You are a bot. Read from ${pluginRoot}/data and ${locations.scopeRoot}.
`;
    await writeFile(helperSourcePath, helperSource);
    await writeFile(botSourcePath, botSource);
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;

    // act
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
      knownSkills: ["acme-helper"],
      mapModel: true,
    });

    // assert
    assert.strictEqual(prepared.kind, "staged");
    assert.deepStrictEqual(prepared.result, {
      stagedNames: ["pi-claude-marketplace-acme-helper", "pi-claude-marketplace-acme-bot"],
      recorded: [
        {
          generatedName: "pi-claude-marketplace-acme-helper",
          sourcePath: helperSourcePath,
          targetPath: helperTargetPath,
        },
        {
          generatedName: "pi-claude-marketplace-acme-bot",
          sourcePath: botSourcePath,
          targetPath: botTargetPath,
        },
      ],
      warnings: [],
      failed: [],
    });
    assert.deepStrictEqual(await readdir(prepared.stagingDir), [
      "pi-claude-marketplace-acme-bot.md",
      "pi-claude-marketplace-acme-helper.md",
    ]);
    assert.strictEqual(
      await readFile(
        path.join(prepared.stagingDir, "pi-claude-marketplace-acme-helper.md"),
        "utf8",
      ),
      expectedHelperBytes,
    );
    assert.strictEqual(
      await readFile(path.join(prepared.stagingDir, "pi-claude-marketplace-acme-bot.md"), "utf8"),
      expectedBotBytes,
    );
  });

  test("aggregates index, conversion, and discovery warnings in stable order", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-stage-warnings-",
    );
    const firstSourcePath = path.join(agentsSourceDir, "first.md");
    const duplicateSourcePath = path.join(agentsSourceDir, "second.md");
    const noisySource = `---
name: noisy
description: Noisy agent
model: future-model
tools: Read,WebFetch
priority: high
---

Noisy body.
`;
    await writeFile(firstSourcePath, noisySource);
    await writeFile(
      duplicateSourcePath,
      `---
name: noisy
description: Duplicate agent
tools: Read
---

Duplicate body.
`,
    );
    await mkdir(locations.extensionRoot, { recursive: true });
    await writeFile(
      locations.agentsIndexPath,
      `${JSON.stringify({ schemaVersion: 1, agents: [{ plugin: "broken" }] }, null, 2)}\n`,
    );
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const generatedName = "pi-claude-marketplace-acme-noisy";
    const expectedWarnings = [
      `agent index corruption (entry dropped): ${locations.agentsIndexPath}.agents[0]: row failed schema validation (entry dropped) -- <root>: must have required properties marketplace, sourceAgent, generatedName, sourcePath, targetPath, sourceHash, droppedFields, droppedTools, warnings`,
      '[noisy] unknown model "future-model" -- omitted from generated frontmatter',
      "[noisy] dropped fields: priority",
      "[noisy] dropped tools: WebFetch",
      `agent source "noisy" in "${agentsSourceDir}" elides to generated name "${generatedName}" already produced by an earlier componentPaths.agents entry; ignoring duplicate.`,
    ];

    // act
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
      mapModel: true,
    });

    // assert
    assert.strictEqual(prepared.kind, "staged");
    assert.deepStrictEqual(prepared.result, {
      stagedNames: [generatedName],
      recorded: [
        {
          generatedName,
          sourcePath: firstSourcePath,
          targetPath: path.join(locations.agentsDir, `${generatedName}.md`),
        },
      ],
      warnings: expectedWarnings,
      failed: [],
    });
  });

  test("surfaces every foreign previous target as a complete failure", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-stage-foreign-",
    );
    const sourcePath = path.join(agentsSourceDir, "reviewer.md");
    await writeFile(
      sourcePath,
      `---
name: reviewer
description: Reviews files
tools: Read
---

Review files.
`,
    );
    const wrongBasenameTarget = path.join(locations.agentsDir, "manual-agent.md");
    const missingMarkerTarget = path.join(
      locations.agentsDir,
      "pi-claude-marketplace-acme-orphan.md",
    );
    await mkdir(locations.agentsDir, { recursive: true });
    await writeFile(
      wrongBasenameTarget,
      "---\nname: manual-agent\n---\ngeneratedBy: pi-claude-marketplace\n",
    );
    await writeFile(missingMarkerTarget, "---\nname: orphan\n---\nManual bytes.\n");
    const index: AgentsIndex = {
      schemaVersion: 1,
      agents: [
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "manual-agent",
          generatedName: "pi-claude-marketplace-acme-manual-agent",
          sourcePath: "/previous/manual-agent.md",
          targetPath: wrongBasenameTarget,
          sourceHash: "hash-manual",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "orphan",
          generatedName: "pi-claude-marketplace-acme-orphan",
          sourcePath: "/previous/orphan.md",
          targetPath: missingMarkerTarget,
          sourceHash: "hash-orphan",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
      ],
    };
    await mkdir(locations.extensionRoot, { recursive: true });
    await writeFile(locations.agentsIndexPath, `${JSON.stringify(index, null, 2)}\n`);
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;

    // act
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
    });

    // assert
    assert.strictEqual(prepared.kind, "staged");
    assert.deepStrictEqual(prepared.result, {
      stagedNames: ["pi-claude-marketplace-acme-reviewer"],
      recorded: [
        {
          generatedName: "pi-claude-marketplace-acme-reviewer",
          sourcePath,
          targetPath: path.join(locations.agentsDir, "pi-claude-marketplace-acme-reviewer.md"),
        },
      ],
      warnings: [],
      failed: [
        {
          generatedName: "pi-claude-marketplace-acme-manual-agent",
          targetPath: wrongBasenameTarget,
          reason: 'target filename "manual-agent.md" does not start with "pi-claude-marketplace-"',
        },
        {
          generatedName: "pi-claude-marketplace-acme-orphan",
          targetPath: missingMarkerTarget,
          reason: `target ${missingMarkerTarget} is missing the generated marker`,
        },
      ],
    });
  });

  test("rejects a generated name owned by another plugin with complete conflict data", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-stage-conflict-",
    );
    const sourcePath = path.join(agentsSourceDir, "reviewer.md");
    await writeFile(
      sourcePath,
      "---\nname: reviewer\ndescription: Reviews files\ntools: Read\n---\n\nReview.\n",
    );
    const conflictingTarget = path.join(
      locations.agentsDir,
      "pi-claude-marketplace-acme-reviewer.md",
    );
    const index: AgentsIndex = {
      schemaVersion: 1,
      agents: [
        {
          plugin: "rival",
          marketplace: "other-catalog",
          sourceAgent: "reviewer",
          generatedName: "pi-claude-marketplace-acme-reviewer",
          sourcePath: "/rival/reviewer.md",
          targetPath: conflictingTarget,
          sourceHash: "hash-rival",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
      ],
    };
    await mkdir(locations.extensionRoot, { recursive: true });
    await writeFile(locations.agentsIndexPath, `${JSON.stringify(index, null, 2)}\n`);
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;

    // act & assert
    await assert.rejects(
      () =>
        prepareStagePluginAgents({
          locations,
          cwd: locations.scopeRoot,
          marketplaceName: "catalog",
          pluginName: "acme",
          pluginRoot,
          pluginDataDir,
          resolved,
          agentsSourceDir,
        }),
      (error: unknown) => {
        assert.ok(error instanceof AgentOwnershipConflictError);
        assert.deepStrictEqual(
          {
            name: error.name,
            message: error.message,
            stagingFor: error.stagingFor,
            conflicts: error.conflicts,
          },
          {
            name: "AgentOwnershipConflictError",
            message:
              'Refusing to stage agents for catalog/acme: "pi-claude-marketplace-acme-reviewer" already owned by other-catalog/rival.',
            stagingFor: { marketplace: "catalog", plugin: "acme" },
            conflicts: [
              {
                generatedName: "pi-claude-marketplace-acme-reviewer",
                owner: { marketplace: "other-catalog", plugin: "rival" },
              },
            ],
          },
        );
        return true;
      },
    );
  });

  test("removes the partial staging directory when a generated filename is too long", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-stage-write-error-",
    );
    const longName = "a".repeat(300);
    await writeFile(
      path.join(agentsSourceDir, "long.md"),
      `---\nname: ${longName}\ndescription: Long name\ntools: Read\n---\n\nBody.\n`,
    );
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;

    // act
    const error = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
    }).then(
      () => undefined,
      (reason: unknown) => reason,
    );
    const stagingEntries = await readdir(locations.agentsStagingDir);

    // assert
    assert.ok(error instanceof Error);
    assert.deepStrictEqual(
      {
        name: error.name,
        code: (error as NodeJS.ErrnoException).code,
        syscall: (error as NodeJS.ErrnoException).syscall,
      },
      { name: "Error", code: "ENAMETOOLONG", syscall: "lstat" },
    );
    assert.deepStrictEqual(stagingEntries, []);
  });
});

describe("commitPreparedAgents", () => {
  test("commits the complete agent-family tree, index, and substitutions", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-commit-family-",
    );
    const helperSource = `---
name: acme-helper
description: Helper agent
tools: Read,Grep
---

Helper body.
`;
    const botSource = `---
name: bot
description: A bot agent
model: sonnet
tools: Read,Bash,Edit
---

You are a bot. Read from \${CLAUDE_PLUGIN_ROOT}/data and \${CLAUDE_PROJECT_DIR}.
`;
    const helperSourcePath = path.join(agentsSourceDir, "acme-helper.md");
    const botSourcePath = path.join(agentsSourceDir, "bot.md");
    const helperTargetPath = path.join(locations.agentsDir, "pi-claude-marketplace-acme-helper.md");
    const botTargetPath = path.join(locations.agentsDir, "pi-claude-marketplace-acme-bot.md");
    const expectedHelperBytes = `---
name: pi-claude-marketplace-acme-helper
description: Helper agent
tools: read,grep
systemPromptMode: replace
inheritProjectContext: true
inheritSkills: false
provenance:
  generatedBy: pi-claude-marketplace
  sourcePlugin: acme
  sourceAgent: acme-helper
  sourcePath: ${helperSourcePath}
  droppedFields: []
  droppedTools: []
  warnings: []
---

Helper body.
`;
    const expectedBotBytes = `---
name: pi-claude-marketplace-acme-bot
description: A bot agent
model: anthropic/claude-sonnet-4-6
tools: read,bash,edit
systemPromptMode: replace
inheritProjectContext: true
inheritSkills: false
provenance:
  generatedBy: pi-claude-marketplace
  sourcePlugin: acme
  sourceAgent: bot
  sourcePath: ${botSourcePath}
  originalModel: sonnet
  droppedFields: []
  droppedTools: []
  warnings: []
---

You are a bot. Read from ${pluginRoot}/data and ${locations.scopeRoot}.
`;
    await writeFile(helperSourcePath, helperSource);
    await writeFile(botSourcePath, botSource);
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const expectedIndex: AgentsIndex = {
      schemaVersion: 1,
      agents: [
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "acme-helper",
          generatedName: "pi-claude-marketplace-acme-helper",
          sourcePath: helperSourcePath,
          targetPath: helperTargetPath,
          sourceHash: "0b95a21a6f2001d5be49907dc52d3d7913aa20e38a73a098a1b8d825fcf8261c",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "bot",
          generatedName: "pi-claude-marketplace-acme-bot",
          sourcePath: botSourcePath,
          targetPath: botTargetPath,
          sourceHash: "971e229318e50e5ad01deb1afcb13fcc883a13632668fd385ad8f1624c69287c",
          originalModel: "sonnet",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
      ],
    };
    const expectedIndexBytes = `${JSON.stringify(expectedIndex, null, 2)}\n`;
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
      knownSkills: ["acme-helper"],
      mapModel: true,
    });

    // act
    const cleanupLeak = await commitPreparedAgents(prepared);

    // assert
    assert.strictEqual(cleanupLeak, undefined);
    assert.deepStrictEqual(await readdir(locations.agentsDir), [
      "pi-claude-marketplace-acme-bot.md",
      "pi-claude-marketplace-acme-helper.md",
    ]);
    assert.strictEqual(await readFile(helperTargetPath, "utf8"), expectedHelperBytes);
    assert.strictEqual(await readFile(botTargetPath, "utf8"), expectedBotBytes);
    assert.strictEqual(await readFile(locations.agentsIndexPath, "utf8"), expectedIndexBytes);
    assert.strictEqual(
      prepared.kind === "staged" ? await exists(prepared.stagingDir) : true,
      false,
    );
  });

  test("removes owned previous files, tolerates missing files, and preserves other owners", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-commit-previous-",
    );
    const sourcePath = path.join(agentsSourceDir, "current.md");
    await writeFile(
      sourcePath,
      "---\nname: current\ndescription: Current agent\ntools: Read\n---\n\nCurrent.\n",
    );
    const ownedTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-old.md");
    const missingTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-missing.md");
    const otherTarget = path.join(locations.agentsDir, "pi-claude-marketplace-other-kept.md");
    await mkdir(locations.agentsDir, { recursive: true });
    await writeFile(
      ownedTarget,
      "---\nname: old\nprovenance:\n  generatedBy: pi-claude-marketplace\n---\n\nOld.\n",
    );
    const previousIndex: AgentsIndex = {
      schemaVersion: 1,
      agents: [
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "old",
          generatedName: "pi-claude-marketplace-acme-old",
          sourcePath: "/previous/old.md",
          targetPath: ownedTarget,
          sourceHash: "hash-old",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "missing",
          generatedName: "pi-claude-marketplace-acme-missing",
          sourcePath: "/previous/missing.md",
          targetPath: missingTarget,
          sourceHash: "hash-missing",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
        {
          plugin: "other",
          marketplace: "other-catalog",
          sourceAgent: "kept",
          generatedName: "pi-claude-marketplace-other-kept",
          sourcePath: "/other/kept.md",
          targetPath: otherTarget,
          sourceHash: "hash-kept",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
      ],
    };
    await mkdir(locations.extensionRoot, { recursive: true });
    await writeFile(locations.agentsIndexPath, `${JSON.stringify(previousIndex, null, 2)}\n`);
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
    });

    // act
    const cleanupLeak = await commitPreparedAgents(prepared);
    const storedIndex = JSON.parse(await readFile(locations.agentsIndexPath, "utf8"));

    // assert
    assert.strictEqual(cleanupLeak, undefined);
    assert.strictEqual(await exists(ownedTarget), false);
    assert.strictEqual(await exists(missingTarget), false);
    assert.strictEqual(
      await exists(path.join(locations.agentsDir, "pi-claude-marketplace-acme-current.md")),
      true,
    );
    assert.deepStrictEqual(storedIndex, {
      schemaVersion: 1,
      agents: [
        previousIndex.agents[2],
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "current",
          generatedName: "pi-claude-marketplace-acme-current",
          sourcePath,
          targetPath: path.join(locations.agentsDir, "pi-claude-marketplace-acme-current.md"),
          sourceHash: "24214fe4c9874b0a54cc773880901f4cac6c6e3c26010846e02c7054b2026249",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
      ],
    });
  });

  test("preserves foreign bytes and their complete index rows", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-commit-foreign-",
    );
    const sourcePath = path.join(agentsSourceDir, "reviewer.md");
    await writeFile(
      sourcePath,
      "---\nname: reviewer\ndescription: Reviews files\ntools: Read\n---\n\nReview.\n",
    );
    const foreignTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-orphan.md");
    const unindexedTarget = path.join(locations.agentsDir, "manual-agent.md");
    const foreignBytes = "---\nname: orphan\n---\nManual bytes.\n";
    const unindexedBytes = "---\nname: manual\n---\nUnindexed bytes.\n";
    await mkdir(locations.agentsDir, { recursive: true });
    await writeFile(foreignTarget, foreignBytes);
    await writeFile(unindexedTarget, unindexedBytes);
    const foreignRow = {
      plugin: "acme",
      marketplace: "catalog",
      sourceAgent: "orphan",
      generatedName: "pi-claude-marketplace-acme-orphan",
      sourcePath: "/previous/orphan.md",
      targetPath: foreignTarget,
      sourceHash: "hash-orphan",
      droppedFields: [],
      droppedTools: [],
      warnings: [],
    } as const;
    await mkdir(locations.extensionRoot, { recursive: true });
    await writeFile(
      locations.agentsIndexPath,
      `${JSON.stringify({ schemaVersion: 1, agents: [foreignRow] }, null, 2)}\n`,
    );
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
    });

    // act
    const cleanupLeak = await commitPreparedAgents(prepared);
    const storedIndex = JSON.parse(await readFile(locations.agentsIndexPath, "utf8"));

    // assert
    assert.strictEqual(cleanupLeak, undefined);
    assert.strictEqual(await readFile(foreignTarget, "utf8"), foreignBytes);
    assert.strictEqual(await readFile(unindexedTarget, "utf8"), unindexedBytes);
    assert.deepStrictEqual(storedIndex, {
      schemaVersion: 1,
      agents: [
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "reviewer",
          generatedName: "pi-claude-marketplace-acme-reviewer",
          sourcePath,
          targetPath: path.join(locations.agentsDir, "pi-claude-marketplace-acme-reviewer.md"),
          sourceHash: "ed65c8a92ce122561217d7cdffbedd53f95f22e25f77f4514bf4af266b16c92d",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
        foreignRow,
      ],
    });
  });

  test("removes staging and leaves prior content when a previous target cannot be removed", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-commit-remove-error-",
    );
    const sourcePath = path.join(agentsSourceDir, "current.md");
    await writeFile(
      sourcePath,
      "---\nname: current\ndescription: Current agent\ntools: Read\n---\n\nCurrent.\n",
    );
    const previousTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-old.md");
    await mkdir(locations.agentsDir, { recursive: true });
    await writeFile(
      previousTarget,
      "---\nname: old\nprovenance:\n  generatedBy: pi-claude-marketplace\n---\n\nOld.\n",
    );
    const previousIndex: AgentsIndex = {
      schemaVersion: 1,
      agents: [
        {
          plugin: "acme",
          marketplace: "catalog",
          sourceAgent: "old",
          generatedName: "pi-claude-marketplace-acme-old",
          sourcePath: "/previous/old.md",
          targetPath: previousTarget,
          sourceHash: "hash-old",
          droppedFields: [],
          droppedTools: [],
          warnings: [],
        },
      ],
    };
    await mkdir(locations.extensionRoot, { recursive: true });
    await writeFile(locations.agentsIndexPath, `${JSON.stringify(previousIndex, null, 2)}\n`);
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
    });
    assert.strictEqual(prepared.kind, "staged");
    await rm(previousTarget);
    await mkdir(previousTarget);
    await writeFile(path.join(previousTarget, "blocker.txt"), "keep");

    // act
    const error = await commitPreparedAgents(prepared).then(
      () => undefined,
      (reason: unknown) => reason,
    );

    // assert
    assert.ok(error instanceof Error);
    assert.deepStrictEqual(
      {
        name: error.name,
        code: (error as NodeJS.ErrnoException).code,
        syscall: (error as NodeJS.ErrnoException).syscall,
      },
      { name: "SystemError", code: "ERR_FS_EISDIR", syscall: "rm" },
    );
    assert.strictEqual(await readFile(path.join(previousTarget, "blocker.txt"), "utf8"), "keep");
    assert.strictEqual(await exists(prepared.stagingDir), false);
    assert.strictEqual(
      await readFile(locations.agentsIndexPath, "utf8"),
      `${JSON.stringify(previousIndex, null, 2)}\n`,
    );
  });

  test("rolls back a partial rename when the next target is blocked", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-commit-rename-error-",
    );
    await writeFile(
      path.join(agentsSourceDir, "alpha.md"),
      "---\nname: alpha\ndescription: Alpha agent\ntools: Read\n---\n\nAlpha.\n",
    );
    await writeFile(
      path.join(agentsSourceDir, "zulu.md"),
      "---\nname: zulu\ndescription: Zulu agent\ntools: Read\n---\n\nZulu.\n",
    );
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
    });
    assert.strictEqual(prepared.kind, "staged");
    await mkdir(locations.agentsDir, { recursive: true });
    const blockedTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-zulu.md");
    await mkdir(blockedTarget);
    await writeFile(path.join(blockedTarget, "blocker.txt"), "keep");

    // act
    const error = await commitPreparedAgents(prepared).then(
      () => undefined,
      (reason: unknown) => reason,
    );

    // assert
    assert.ok(error instanceof Error);
    assert.deepStrictEqual(
      {
        name: error.name,
        code: (error as NodeJS.ErrnoException).code,
        syscall: (error as NodeJS.ErrnoException).syscall,
      },
      { name: "Error", code: "EISDIR", syscall: "rename" },
    );
    assert.deepStrictEqual(await readdir(locations.agentsDir), [
      "pi-claude-marketplace-acme-zulu.md",
    ]);
    assert.strictEqual(await readFile(path.join(blockedTarget, "blocker.txt"), "utf8"), "keep");
    assert.strictEqual(await exists(prepared.stagingDir), false);
    assert.strictEqual(await exists(locations.agentsIndexPath), false);
  });
});

describe("abortPreparedAgents", () => {
  test("returns without materializing paths for a no-op prepare", async (t) => {
    // arrange
    const { pluginRoot, locations, pluginDataDir } = await createStageTree(t, "agents-abort-noop-");
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: [],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: [] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir: null,
    });

    // act
    const cleanupLeak = await abortPreparedAgents(prepared);

    // assert
    assert.strictEqual(cleanupLeak, undefined);
    assert.strictEqual(await exists(locations.agentsDir), false);
    assert.strictEqual(await exists(locations.agentsIndexPath), false);
  });

  test("removes staged files without touching agent targets", async (t) => {
    // arrange
    const { pluginRoot, agentsSourceDir, locations, pluginDataDir } = await createStageTree(
      t,
      "agents-abort-staged-",
    );
    await writeFile(
      path.join(agentsSourceDir, "reviewer.md"),
      "---\nname: reviewer\ndescription: Reviews files\ntools: Read\n---\n\nReview.\n",
    );
    const resolved = {
      installable: true,
      state: "installable",
      name: "acme",
      pluginRoot,
      supported: ["agents"],
      unsupported: [],
      notes: [],
      componentPaths: { skills: [], commands: [], agents: ["agents"] },
      mcpServers: {},
      defaultEnabled: true,
    } satisfies ResolvedPluginInstallable;
    const prepared = await prepareStagePluginAgents({
      locations,
      cwd: locations.scopeRoot,
      marketplaceName: "catalog",
      pluginName: "acme",
      pluginRoot,
      pluginDataDir,
      resolved,
      agentsSourceDir,
    });
    assert.strictEqual(prepared.kind, "staged");

    // act
    const cleanupLeak = await abortPreparedAgents(prepared);

    // assert
    assert.strictEqual(cleanupLeak, undefined);
    assert.strictEqual(await exists(prepared.stagingDir), false);
    assert.strictEqual(await exists(locations.agentsDir), false);
    assert.strictEqual(await exists(locations.agentsIndexPath), false);
  });
});
