import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test, { type TestContext } from "node:test";

import { unstagePluginAgents } from "../../../extensions/pi-claude-marketplace/bridges/agents/unstage.ts";
import { locationsFor } from "../../../extensions/pi-claude-marketplace/persistence/locations.ts";

import type {
  AgentsIndex,
  AgentsIndexEntry,
} from "../../../extensions/pi-claude-marketplace/persistence/agents-index-schema.ts";

async function createScope(t: TestContext, prefix: string) {
  const directory = await mkdtemp(path.join(tmpdir(), prefix));
  t.after(() => rm(directory, { recursive: true, force: true, maxRetries: 3 }));
  return locationsFor("project", directory);
}

test("removes owned current and legacy agents while preserving foreign and other-plugin entries", async (t) => {
  // arrange
  const locations = await createScope(t, "agents-unstage-owned-");
  const currentTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-current.md");
  const legacyTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-legacy.md");
  const foreignTarget = path.join(locations.agentsDir, "pi-claude-marketplace-acme-foreign.md");
  const otherTarget = path.join(locations.agentsDir, "pi-claude-marketplace-other-agent.md");
  const currentBytes =
    "---\nname: pi-claude-marketplace-acme-current\nprovenance:\n  generatedBy: pi-claude-marketplace\n---\n\nCurrent.\n";
  const legacyBytes =
    "---\nname: pi-claude-marketplace-acme-legacy\n---\n\n<!-- generated by pi-claude-marketplace -->\n\nLegacy.\n";
  const foreignBytes = "---\nname: pi-claude-marketplace-acme-foreign\n---\n\nForeign.\n";
  const otherBytes =
    "---\nname: pi-claude-marketplace-other-agent\nprovenance:\n  generatedBy: pi-claude-marketplace\n---\n\nOther.\n";
  const currentEntry: AgentsIndexEntry = {
    plugin: "acme",
    marketplace: "catalog",
    sourceAgent: "current",
    generatedName: "pi-claude-marketplace-acme-current",
    sourcePath: "/plugins/acme/agents/current.md",
    targetPath: currentTarget,
    sourceHash: "current-hash",
    originalModel: "sonnet",
    droppedFields: ["color"],
    droppedTools: ["WebFetch"],
    warnings: ["current warning"],
  };
  const legacyEntry: AgentsIndexEntry = {
    plugin: "acme",
    marketplace: "catalog",
    sourceAgent: "legacy",
    generatedName: "pi-claude-marketplace-acme-legacy",
    sourcePath: "/plugins/acme/agents/legacy.md",
    targetPath: legacyTarget,
    sourceHash: "legacy-hash",
    droppedFields: [],
    droppedTools: [],
    warnings: [],
  };
  const foreignEntry: AgentsIndexEntry = {
    plugin: "acme",
    marketplace: "catalog",
    sourceAgent: "foreign",
    generatedName: "pi-claude-marketplace-acme-foreign",
    sourcePath: "/plugins/acme/agents/foreign.md",
    targetPath: foreignTarget,
    sourceHash: "foreign-hash",
    droppedFields: [],
    droppedTools: [],
    warnings: ["keep foreign"],
  };
  const otherEntry: AgentsIndexEntry = {
    plugin: "other",
    marketplace: "catalog",
    sourceAgent: "agent",
    generatedName: "pi-claude-marketplace-other-agent",
    sourcePath: "/plugins/other/agents/agent.md",
    targetPath: otherTarget,
    sourceHash: "other-hash",
    droppedFields: [],
    droppedTools: [],
    warnings: [],
  };
  const storedIndex: AgentsIndex = {
    schemaVersion: 1,
    agents: [currentEntry, otherEntry, legacyEntry, foreignEntry],
  };
  const expectedIndex: AgentsIndex = {
    schemaVersion: 1,
    agents: [otherEntry, foreignEntry],
  };
  const expectedIndexBytes = `${JSON.stringify(expectedIndex, null, 2)}\n`;
  await mkdir(locations.agentsDir, { recursive: true });
  await mkdir(locations.extensionRoot, { recursive: true });
  await writeFile(currentTarget, currentBytes);
  await writeFile(legacyTarget, legacyBytes);
  await writeFile(foreignTarget, foreignBytes);
  await writeFile(otherTarget, otherBytes);
  await writeFile(locations.agentsIndexPath, JSON.stringify(storedIndex));

  // act
  const unstagedAgents = await unstagePluginAgents({
    locations,
    marketplaceName: "catalog",
    pluginName: "acme",
  });
  const agentFiles = await readdir(locations.agentsDir);
  const retainedForeignBytes = await readFile(foreignTarget, "utf8");
  const retainedOtherBytes = await readFile(otherTarget, "utf8");
  const indexBytes = await readFile(locations.agentsIndexPath, "utf8");

  // assert
  assert.deepStrictEqual(unstagedAgents, {
    removedNames: ["pi-claude-marketplace-acme-current", "pi-claude-marketplace-acme-legacy"],
    failed: [
      {
        generatedName: "pi-claude-marketplace-acme-foreign",
        targetPath: foreignTarget,
        reason: `target ${foreignTarget} is missing the generated marker`,
      },
    ],
    warnings: [],
  });
  assert.deepStrictEqual(agentFiles.sort(), [
    "pi-claude-marketplace-acme-foreign.md",
    "pi-claude-marketplace-other-agent.md",
  ]);
  assert.strictEqual(retainedForeignBytes, foreignBytes);
  assert.strictEqual(retainedOtherBytes, otherBytes);
  assert.strictEqual(indexBytes, expectedIndexBytes);
});
