import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";

import {
  GENERATED_AGENT_MARKER,
  GENERATED_AGENT_MARKER_LEGACY,
  GENERATED_AGENT_PREFIX,
} from "../../extensions/pi-claude-marketplace/bridges/agents/marker.ts";
import { locationsFor } from "../../extensions/pi-claude-marketplace/persistence/locations.ts";
import * as markers from "../../extensions/pi-claude-marketplace/shared/markers.ts";

/**
 * The AG-5 / PUP-6 / D-08 snapshot assertions below enforce drift on the
 * exported markers in shared/markers.ts.
 *
 * Re-introductions of any of the 5 superseded ES-5 literals anywhere in
 * the codebase are blocked by tests/architecture/no-legacy-markers.test.ts
 * (D-13-12), which pins the literals in its own body and
 * runs under `npm run check`.
 */

/**
 * AG-5 user contract: the agents-bridge marker constants. These ARE the
 * substrings that every staged agent file's basename and body must contain;
 * any drift would silently invalidate every existing user's previously-staged
 * agent files (the safety check would reject them as foreign content). The
 * current signature is the `generatedBy` frontmatter value; the legacy
 * signature is retained so pre-0.10 body-comment files stay recognized.
 *
 * Byte-for-byte equality. DO NOT EDIT without an explicit user-facing
 * migration.
 */
test("AG-5 GENERATED_AGENT_MARKER is byte-for-byte 'generatedBy: pi-claude-marketplace'", () => {
  assert.equal(GENERATED_AGENT_MARKER, "generatedBy: pi-claude-marketplace");
});

test("AG-5 GENERATED_AGENT_MARKER_LEGACY is byte-for-byte 'generated by pi-claude-marketplace'", () => {
  assert.equal(GENERATED_AGENT_MARKER_LEGACY, "generated by pi-claude-marketplace");
});

test("AG-5 GENERATED_AGENT_PREFIX is byte-for-byte 'pi-claude-marketplace-'", () => {
  assert.equal(GENERATED_AGENT_PREFIX, "pi-claude-marketplace-");
});

/**
 * PUP-6 recovery-hint prefix.
 *
 * D-04: The PRD §5.2.3 PUP-6 row specifies the
 * user-visible composition as `plugin-uninstall + plugin-install for
 * "<plugin-name>".`. The runtime callsite supplies the leading space +
 * quoted name, so the exported prefix is byte-for-byte the substring up
 * to (but not including) the space before the quote.
 */
test("PUP-6 recovery-hint prefix is byte-for-byte 'plugin-uninstall + plugin-install for'", () => {
  assert.equal(markers.RECOVERY_PLUGIN_REINSTALL_PREFIX, "plugin-uninstall + plugin-install for");
});

/**
 * D-08 state-lock marker.
 *
 * It is a user-contract prefix for
 * fail-fast cross-process lock contention.
 */
test("D-08 state-lock-held prefix is byte-for-byte 'Another pi-claude-marketplace operation is in progress for'", () => {
  assert.equal(
    markers.STATE_LOCK_HELD_PREFIX,
    "Another pi-claude-marketplace operation is in progress for",
  );
});

test("D-09 state lock file is the .state-lock sentinel below extensionRoot", () => {
  const locations = locationsFor("project", "/tmp/pi-project");

  assert.equal(locations.stateLockFile, path.join(locations.extensionRoot, ".state-lock"));
});
