import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";

import {
  GENERATED_AGENT_MARKER,
  GENERATED_AGENT_MARKER_LEGACY,
  GENERATED_AGENT_PREFIX,
} from "../../extensions/pi-claude-marketplace/bridges/agents/marker.ts";
import { locationsFor } from "../../extensions/pi-claude-marketplace/persistence/locations.ts";

/**
 * Drift snapshot for the AG-5 agents-bridge marker values, which are user
 * contract, plus the D-09 state-lock path, which is a relationship between two
 * `locationsFor` getters rather than a property of any single export.
 *
 * The PUP-6 recovery-hint and D-08 state-lock-contention prefixes exported by
 * `shared/markers.ts` are pinned byte-for-byte by that module's owner test,
 * `tests/shared/markers.test.ts`.
 */

/**
 * AG-5 user contract: the agents-bridge marker constants. These ARE the
 * substrings that every staged agent file's basename and body must contain;
 * any drift would silently invalidate every existing user's previously-staged
 * agent files (the safety check would reject them as foreign content). The
 * current signature is the `generatedBy` frontmatter value; the legacy
 * signature is retained so pre-0.10 body-comment files stay recognized.
 *
 * Byte-for-byte equality. DO NOT EDIT without an explicit user-facing
 * migration.
 */
test("AG-5 GENERATED_AGENT_MARKER is byte-for-byte 'generatedBy: pi-claude-marketplace'", () => {
  assert.equal(GENERATED_AGENT_MARKER, "generatedBy: pi-claude-marketplace");
});

test("AG-5 GENERATED_AGENT_MARKER_LEGACY is byte-for-byte 'generated by pi-claude-marketplace'", () => {
  assert.equal(GENERATED_AGENT_MARKER_LEGACY, "generated by pi-claude-marketplace");
});

test("AG-5 GENERATED_AGENT_PREFIX is byte-for-byte 'pi-claude-marketplace-'", () => {
  assert.equal(GENERATED_AGENT_PREFIX, "pi-claude-marketplace-");
});

test("D-09 state lock file is the .state-lock sentinel below extensionRoot", () => {
  const locations = locationsFor("project", "/tmp/pi-project");

  assert.equal(locations.stateLockFile, path.join(locations.extensionRoot, ".state-lock"));
});
