// bridges/agents/marker.ts
//
// AG-5 two-part marker check + user-contract constants.
//
// The isOwnedAgentFile algorithm lives in a testable module. The marker
// constants are byte-for-byte user contract -- the markers-snapshot
// architectural test asserts equality, and any drift would silently break
// every existing user's previously-staged agent files.
//
// Two marker formats are recognized so no already-installed agent is
// orphaned across the 0.10 provenance change:
//   - GENERATED_AGENT_MARKER is the current-format signature, emitted by
//     frontmatter.ts as the `provenance.generatedBy` frontmatter line.
//   - GENERATED_AGENT_MARKER_LEGACY is the pre-0.10 signature that lived in
//     the body HTML comment. Old on-disk files still carry it.
//
// T-03-25 mitigation: a foreign file claiming the basename without either
// marker fails the body check; a foreign file with a marker but the wrong
// basename fails the basename check. Both gates must pass.

import { readFile } from "node:fs/promises";
import path from "node:path";

/** AG-5 user contract: basename prefix every staged agent file MUST start with. */
export const GENERATED_AGENT_PREFIX = "pi-claude-marketplace-";

/**
 * AG-5 user contract: substring every current-format staged agent MUST
 * contain. This is exactly the emitted `provenance.generatedBy` line, so
 * frontmatter.ts builds that line as `  ${GENERATED_AGENT_MARKER}`.
 * DO NOT EDIT -- value is asserted by markers-snapshot test.
 */
export const GENERATED_AGENT_MARKER = "generatedBy: pi-claude-marketplace";

/**
 * AG-5 back-compat: substring every pre-0.10 staged agent carries in its
 * body HTML comment. Retained so already-installed old-format agents stay
 * recognized without a migration. DO NOT EDIT -- value is asserted by
 * markers-snapshot test.
 */
export const GENERATED_AGENT_MARKER_LEGACY = "generated by pi-claude-marketplace";

export type SafetyResult = { ok: true } | { ok: false; reason: string };

/**
 * AG-5 two-part marker check: basename starts with `pi-claude-marketplace-`
 * AND body contains EITHER marker (current `generatedBy: ...` signature or
 * the legacy body-comment phrase). Either check failing means the file is
 * foreign content -- refuse to touch.
 *
 * Missing file (ENOENT) -> ok:true (nothing to refuse). Caller decides
 * whether the absence is a problem in its own context.
 *
 * Other I/O errors (EACCES, EISDIR) propagate to caller.
 */
export async function isOwnedAgentFile(targetPath: string): Promise<SafetyResult> {
  const base = path.basename(targetPath);
  if (!base.startsWith(GENERATED_AGENT_PREFIX)) {
    return {
      ok: false,
      reason: `target filename "${base}" does not start with "${GENERATED_AGENT_PREFIX}"`,
    };
  }

  let contents: string;
  try {
    contents = await readFile(targetPath, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      return { ok: true };
    }

    throw err;
  }

  if (
    !contents.includes(GENERATED_AGENT_MARKER) &&
    !contents.includes(GENERATED_AGENT_MARKER_LEGACY)
  ) {
    return {
      ok: false,
      reason: `target ${targetPath} is missing the generated marker`,
    };
  }

  return { ok: true };
}
