// Shared raw -> written -> Claude-output cases for plugin MCP variables
// (AVAR-01..03, AVAR-05). Each row is one raw field value, the environment at
// install, the value this extension writes, the environment when the server
// connects, and Claude Code's output for that field, derived by hand from
// Claude's rule. `substitute.test.ts` checks `written`, `missing` and
// `blanked`. The adapter conformance
// test feeds `written` through pi-mcp-adapter's real call chain for `field`
// with `PI_CLAUDE_MARKETPLACE_EMPTY=""` and `runtimeEnv`, and expects
// `claudeOutput`. Every reference a row keeps is set in `runtimeEnv`.

/** Where a raw value sits in the translated entry. */
export type ExpansionField =
  | "command"
  | "args"
  | "env"
  | "env-builtin"
  | "url"
  | "headers"
  | "oauth.clientId"
  | "oauth.scope"
  | "oauth.authServerMetadataUrl";

/** One field value's expected install-time and runtime behavior. */
export interface ExpansionCase {
  readonly title: string;
  readonly field: ExpansionField;
  /** The install scope; project when absent. */
  readonly scope?: "user" | "project";
  readonly raw: string;
  readonly installEnv: Readonly<Record<string, string>>;
  readonly written: string;
  readonly missing: readonly string[];
  /** The set deny-listed names withheld from `url` or `headers`; none when absent. */
  readonly blanked?: readonly string[];
  readonly runtimeEnv: Readonly<Record<string, string>>;
  readonly claudeOutput: string;
}

/** The builtin paths every case expands against. */
export const EXPANSION_BUILTINS = {
  pluginRoot: "/plugins/acme",
  pluginData: "/data/mp/acme",
  projectDir: "/work/project",
} as const;

const SPLIT = "{env:PI_CLAUDE_MARKETPLACE_EMPTY}";

const SECRET_ENV = { PI_CM_SECRET: "secret-value" };

export const EXPANSION_CASES: readonly ExpansionCase[] = [
  {
    title: "AVAR-01: command ${CLAUDE_PLUGIN_ROOT} becomes the plugin root",
    field: "command",
    raw: "${CLAUDE_PLUGIN_ROOT}/bin/server",
    installEnv: {},
    written: "/plugins/acme/bin/server",
    missing: [],
    runtimeEnv: {},
    claudeOutput: "/plugins/acme/bin/server",
  },
  {
    title: "AVAR-01: args ${CLAUDE_PROJECT_DIR} becomes the project root at project scope",
    field: "args",
    raw: "${CLAUDE_PROJECT_DIR}",
    installEnv: {},
    written: "/work/project",
    missing: [],
    runtimeEnv: {},
    claudeOutput: "/work/project",
  },
  {
    title: "AVAR-01: args ${CLAUDE_PROJECT_DIR} stays a reference at user scope",
    field: "args",
    scope: "user",
    raw: "${CLAUDE_PROJECT_DIR}",
    installEnv: {},
    written: "${CLAUDE_PROJECT_DIR}",
    missing: [],
    runtimeEnv: { CLAUDE_PROJECT_DIR: "/work/project" },
    claudeOutput: "/work/project",
  },
  {
    title: "AVAR-02: args with a variable unset at install keeps the reference and reports it",
    field: "args",
    raw: "--site=${PI_CM_SITE}",
    installEnv: {},
    written: "--site=${PI_CM_SITE}",
    missing: ["PI_CM_SITE"],
    runtimeEnv: { PI_CM_SITE: "us5" },
    claudeOutput: "--site=us5",
  },
  {
    title: "AVAR-02: args ${VAR:-default} with the variable unset writes the default",
    field: "args",
    raw: "${PI_CM_LEVEL:-info}",
    installEnv: {},
    written: "info",
    missing: [],
    runtimeEnv: {},
    claudeOutput: "info",
  },
  {
    title: "AVAR-02: args ${VAR:-default} with the variable set to empty keeps the reference",
    field: "args",
    raw: "${PI_CM_LEVEL:-info}",
    installEnv: { PI_CM_LEVEL: "" },
    written: "${PI_CM_LEVEL}",
    missing: [],
    runtimeEnv: { PI_CM_LEVEL: "" },
    claudeOutput: "",
  },
  {
    title: "AVAR-02: headers with a set variable keeps the reference",
    field: "headers",
    raw: "Bearer ${PI_CM_TOKEN}",
    installEnv: { PI_CM_TOKEN: "token-value" },
    written: "Bearer ${PI_CM_TOKEN}",
    missing: [],
    runtimeEnv: { PI_CM_TOKEN: "token-value" },
    claudeOutput: "Bearer token-value",
  },
  {
    title: "AVAR-02: headers ${VAR:-} with the variable unset writes an empty value",
    field: "headers",
    raw: "${DD_API_KEY:-}",
    installEnv: {},
    written: "",
    missing: [],
    runtimeEnv: {},
    claudeOutput: "",
  },
  {
    title: "AVAR-02: url ${VAR:-default} with the variable unset writes the default",
    field: "url",
    raw: "${LOGFIRE_MCP_URL:-https://logfire-us.pydantic.dev/mcp}",
    installEnv: {},
    written: "https://logfire-us.pydantic.dev/mcp",
    missing: [],
    runtimeEnv: {},
    claudeOutput: "https://logfire-us.pydantic.dev/mcp",
  },
  {
    title: "AVAR-02: url ${VAR:-default} with the variable set keeps the reference",
    field: "url",
    raw: "${LOGFIRE_MCP_URL:-https://logfire-us.pydantic.dev/mcp}",
    installEnv: { LOGFIRE_MCP_URL: "https://logfire-eu.example.test/mcp" },
    written: "${LOGFIRE_MCP_URL}",
    missing: [],
    runtimeEnv: { LOGFIRE_MCP_URL: "https://logfire-eu.example.test/mcp" },
    claudeOutput: "https://logfire-eu.example.test/mcp",
  },
  {
    title: "AVAR-03: headers literal {env:NAME} is split",
    field: "headers",
    raw: "{env:PI_CM_SECRET}",
    installEnv: {},
    written: `{env:${SPLIT}PI_CM_SECRET}`,
    missing: [],
    runtimeEnv: SECRET_ENV,
    claudeOutput: "{env:PI_CM_SECRET}",
  },
  {
    title: "AVAR-03: headers literal $env:NAME is split",
    field: "headers",
    raw: "$env:PI_CM_SECRET",
    installEnv: {},
    written: `$env${SPLIT}:PI_CM_SECRET`,
    missing: [],
    runtimeEnv: SECRET_ENV,
    claudeOutput: "$env:PI_CM_SECRET",
  },
  {
    title: "AVAR-03: env literal ${1X} is split",
    field: "env",
    raw: "${1X}",
    installEnv: {},
    written: `$${SPLIT}{1X}`,
    missing: [],
    runtimeEnv: { "1X": "x" },
    claudeOutput: "${1X}",
  },
  {
    title: "AVAR-03: env value starting with ! gains one !",
    field: "env",
    raw: "!echo hi",
    installEnv: {},
    written: "!!echo hi",
    missing: [],
    runtimeEnv: {},
    claudeOutput: "!echo hi",
  },
  {
    title: "AVAR-03: env ! before a kept reference gains one !",
    field: "env",
    raw: "!${PI_CM_CMD}",
    installEnv: { PI_CM_CMD: "x" },
    written: "!!${PI_CM_CMD}",
    missing: [],
    runtimeEnv: { PI_CM_CMD: "x" },
    claudeOutput: "!x",
  },
  {
    title: "AVAR-01: env CLAUDE_PLUGIN_ROOT value is literal",
    field: "env-builtin",
    raw: "${PI_CM_FOO}",
    installEnv: {},
    written: `$${SPLIT}{PI_CM_FOO}`,
    missing: [],
    runtimeEnv: { PI_CM_FOO: "x" },
    claudeOutput: "${PI_CM_FOO}",
  },
  {
    title: "AVAR-01: oauth.clientId is literal",
    field: "oauth.clientId",
    raw: "${PI_CM_SECRET}",
    installEnv: SECRET_ENV,
    written: `$${SPLIT}{PI_CM_SECRET}`,
    missing: [],
    runtimeEnv: SECRET_ENV,
    claudeOutput: "${PI_CM_SECRET}",
  },
  {
    title: "AVAR-01: oauth.scope is literal",
    field: "oauth.scope",
    raw: "{env:PI_CM_SECRET} read",
    installEnv: {},
    written: `{env:${SPLIT}PI_CM_SECRET} read`,
    missing: [],
    runtimeEnv: SECRET_ENV,
    claudeOutput: "{env:PI_CM_SECRET} read",
  },
  {
    title: "AVAR-01: oauth.authServerMetadataUrl is literal",
    field: "oauth.authServerMetadataUrl",
    raw: "https://auth.example.test/$env:PI_CM_SECRET",
    installEnv: {},
    written: `https://auth.example.test/$env${SPLIT}:PI_CM_SECRET`,
    missing: [],
    runtimeEnv: SECRET_ENV,
    claudeOutput: "https://auth.example.test/$env:PI_CM_SECRET",
  },
  {
    title: "AVAR-03: headers {env before an empty reference is guarded",
    field: "headers",
    raw: "{env${PI_CM_R}:PI_CM_SECRET}",
    installEnv: { PI_CM_R: "" },
    written: `{env${SPLIT}\${PI_CM_R}${SPLIT}:PI_CM_SECRET}`,
    missing: [],
    runtimeEnv: { ...SECRET_ENV, PI_CM_R: "" },
    claudeOutput: "{env:PI_CM_SECRET}",
  },
  {
    title: "AVAR-03: headers $en before an empty reference is guarded",
    field: "headers",
    raw: "$en${PI_CM_R}v:PI_CM_SECRET",
    installEnv: { PI_CM_R: "" },
    written: `$en${SPLIT}\${PI_CM_R}${SPLIT}v:PI_CM_SECRET`,
    missing: [],
    runtimeEnv: { ...SECRET_ENV, PI_CM_R: "" },
    claudeOutput: "$env:PI_CM_SECRET",
  },
  {
    title: "AVAR-03: headers default text and adjacent literal text are escaped as one run",
    field: "headers",
    raw: "${PI_CM_A:-{}env:PI_CM_SECRET}",
    installEnv: {},
    written: `{env:${SPLIT}PI_CM_SECRET}`,
    missing: [],
    runtimeEnv: SECRET_ENV,
    claudeOutput: "{env:PI_CM_SECRET}",
  },
  {
    title: "AVAR-03: headers nested {env:{env:NAME}} is split twice",
    field: "headers",
    raw: "{env:{env:PI_CM_SECRET}}",
    installEnv: {},
    written: `{env:${SPLIT}{env:${SPLIT}PI_CM_SECRET}}`,
    missing: [],
    runtimeEnv: SECRET_ENV,
    claudeOutput: "{env:{env:PI_CM_SECRET}}",
  },
  {
    title: "AVAR-01: args ~user/x is literal and the adapter leaves it",
    field: "args",
    raw: "~user/x",
    installEnv: {},
    written: "~user/x",
    missing: [],
    runtimeEnv: {},
    claudeOutput: "~user/x",
  },
  {
    title: "AVAR-05: headers set ANTHROPIC_API_KEY inside text is written empty",
    field: "headers",
    raw: "Bearer ${ANTHROPIC_API_KEY}",
    installEnv: { ANTHROPIC_API_KEY: "api-key-value" },
    written: "Bearer ",
    missing: [],
    blanked: ["ANTHROPIC_API_KEY"],
    runtimeEnv: { ANTHROPIC_API_KEY: "api-key-value" },
    claudeOutput: "Bearer ",
  },
  {
    title: "AVAR-05: headers ANTHROPIC_API_KEY ignores its default",
    field: "headers",
    raw: "${ANTHROPIC_API_KEY:-fallback}",
    installEnv: {},
    written: "",
    missing: [],
    runtimeEnv: { ANTHROPIC_API_KEY: "later-value" },
    claudeOutput: "",
  },
  {
    title: "AVAR-05: url unset AWS_SESSION_TOKEN is written empty and never missing",
    field: "url",
    raw: "https://mcp.example.test/?k=${AWS_SESSION_TOKEN}",
    installEnv: {},
    written: "https://mcp.example.test/?k=",
    missing: [],
    runtimeEnv: { AWS_SESSION_TOKEN: "later-value" },
    claudeOutput: "https://mcp.example.test/?k=",
  },
  {
    title: "AVAR-05: env set ANTHROPIC_API_KEY keeps the reference",
    field: "env",
    raw: "${ANTHROPIC_API_KEY}",
    installEnv: { ANTHROPIC_API_KEY: "api-key-value" },
    written: "${ANTHROPIC_API_KEY}",
    missing: [],
    runtimeEnv: { ANTHROPIC_API_KEY: "api-key-value" },
    claudeOutput: "api-key-value",
  },
  {
    title: "AVAR-05: env set CLAUDE_CODE_OAUTH_TOKEN is written empty",
    field: "env",
    raw: "${CLAUDE_CODE_OAUTH_TOKEN}",
    installEnv: { CLAUDE_CODE_OAUTH_TOKEN: "oauth-token-value" },
    written: "",
    missing: [],
    runtimeEnv: { CLAUDE_CODE_OAUTH_TOKEN: "oauth-token-value" },
    claudeOutput: "",
  },
  {
    title: "AVAR-05: env unset CLAUDE_CODE_OAUTH_TOKEN is the split-token literal and missing",
    field: "env",
    raw: "${CLAUDE_CODE_OAUTH_TOKEN}",
    installEnv: {},
    written: `$${SPLIT}{CLAUDE_CODE_OAUTH_TOKEN}`,
    missing: ["CLAUDE_CODE_OAUTH_TOKEN"],
    runtimeEnv: {},
    claudeOutput: "${CLAUDE_CODE_OAUTH_TOKEN}",
  },
  {
    title: "AVAR-05: headers set lowercase otel_exporter_otlp_headers is written empty",
    field: "headers",
    raw: "${otel_exporter_otlp_headers}",
    installEnv: { otel_exporter_otlp_headers: "otel-value" },
    written: "",
    missing: [],
    blanked: ["otel_exporter_otlp_headers"],
    runtimeEnv: { otel_exporter_otlp_headers: "otel-value" },
    claudeOutput: "",
  },
  {
    title: "AVAR-05: headers set INPUT_NPM_TOKEN is written empty",
    field: "headers",
    raw: "${INPUT_NPM_TOKEN}",
    installEnv: { INPUT_NPM_TOKEN: "npm-token-value" },
    written: "",
    missing: [],
    blanked: ["INPUT_NPM_TOKEN"],
    runtimeEnv: { INPUT_NPM_TOKEN: "npm-token-value" },
    claudeOutput: "",
  },
  {
    title: "AVAR-05: url set GIT_CONFIG_VALUE_0 is written empty",
    field: "url",
    raw: "https://mcp.example.test/${GIT_CONFIG_VALUE_0}",
    installEnv: { GIT_CONFIG_VALUE_0: "config-value" },
    written: "https://mcp.example.test/",
    missing: [],
    blanked: ["GIT_CONFIG_VALUE_0"],
    runtimeEnv: { GIT_CONFIG_VALUE_0: "config-value" },
    claudeOutput: "https://mcp.example.test/",
  },
  {
    title: "AVAR-05: headers set CARGO_REGISTRIES_MY_REG_TOKEN is written empty",
    field: "headers",
    raw: "${CARGO_REGISTRIES_MY_REG_TOKEN}",
    installEnv: { CARGO_REGISTRIES_MY_REG_TOKEN: "cargo-token-value" },
    written: "",
    missing: [],
    blanked: ["CARGO_REGISTRIES_MY_REG_TOKEN"],
    runtimeEnv: { CARGO_REGISTRIES_MY_REG_TOKEN: "cargo-token-value" },
    claudeOutput: "",
  },
  {
    title: "AVAR-05: headers ANTHROPIC_BASE_URL holding a credential is written empty",
    field: "headers",
    raw: "${ANTHROPIC_BASE_URL}",
    installEnv: { ANTHROPIC_BASE_URL: "https://user:pass@proxy.example.test" },
    written: "",
    missing: [],
    blanked: ["ANTHROPIC_BASE_URL"],
    runtimeEnv: { ANTHROPIC_BASE_URL: "https://user:pass@proxy.example.test" },
    claudeOutput: "",
  },
  {
    title: "AVAR-05: headers credential-free ANTHROPIC_BASE_URL keeps the reference",
    field: "headers",
    raw: "${ANTHROPIC_BASE_URL}",
    installEnv: { ANTHROPIC_BASE_URL: "https://proxy.example.test" },
    written: "${ANTHROPIC_BASE_URL}",
    missing: [],
    runtimeEnv: { ANTHROPIC_BASE_URL: "https://proxy.example.test" },
    claudeOutput: "https://proxy.example.test",
  },
  {
    title: "AVAR-05: headers set GITHUB_TOKEN keeps the reference",
    field: "headers",
    raw: "${GITHUB_TOKEN}",
    installEnv: { GITHUB_TOKEN: "github-token-value" },
    written: "${GITHUB_TOKEN}",
    missing: [],
    runtimeEnv: { GITHUB_TOKEN: "github-token-value" },
    claudeOutput: "github-token-value",
  },
  {
    title: "AVAR-05: headers {env before an empty reference cannot compose {env:ANTHROPIC_API_KEY}",
    field: "headers",
    raw: "{env${PI_CM_R}:ANTHROPIC_API_KEY}",
    installEnv: { PI_CM_R: "" },
    written: `{env${SPLIT}\${PI_CM_R}${SPLIT}:ANTHROPIC_API_KEY}`,
    missing: [],
    runtimeEnv: { ANTHROPIC_API_KEY: "api-key-value", PI_CM_R: "" },
    claudeOutput: "{env:ANTHROPIC_API_KEY}",
  },
  {
    title: "AVAR-05: headers {env around a withheld reference is escaped as one run",
    field: "headers",
    raw: "{env${ANTHROPIC_API_KEY}:PI_CM_SECRET}",
    installEnv: { ANTHROPIC_API_KEY: "api-key-value" },
    written: `{env:${SPLIT}PI_CM_SECRET}`,
    missing: [],
    blanked: ["ANTHROPIC_API_KEY"],
    runtimeEnv: { ...SECRET_ENV, ANTHROPIC_API_KEY: "api-key-value" },
    claudeOutput: "{env:PI_CM_SECRET}",
  },
  {
    title:
      "AVAR-05: headers env: after a reference ending in $ cannot compose $env:ANTHROPIC_API_KEY",
    field: "headers",
    raw: "${PSX}env:ANTHROPIC_API_KEY",
    installEnv: { PSX: "abc$" },
    written: `\${PSX}${SPLIT}env:ANTHROPIC_API_KEY`,
    missing: [],
    runtimeEnv: { PSX: "abc$", ANTHROPIC_API_KEY: "api-key-value" },
    claudeOutput: "abc$env:ANTHROPIC_API_KEY",
  },
  {
    title: "AVAR-05: url : after a reference ending in $env cannot compose $env:ANTHROPIC_API_KEY",
    field: "url",
    raw: "https://mcp.example.test/${PI_CM_P}:ANTHROPIC_API_KEY",
    installEnv: { PI_CM_P: "p$env" },
    written: `https://mcp.example.test/\${PI_CM_P}${SPLIT}:ANTHROPIC_API_KEY`,
    missing: [],
    runtimeEnv: { PI_CM_P: "p$env", ANTHROPIC_API_KEY: "api-key-value" },
    claudeOutput: "https://mcp.example.test/p$env:ANTHROPIC_API_KEY",
  },
  {
    title:
      "AVAR-05: headers a name after a reference ending in {env: cannot compose {env:ANTHROPIC_API_KEY}",
    field: "headers",
    raw: "${PI_CM_P}ANTHROPIC_API_KEY}",
    installEnv: { PI_CM_P: "p{env:" },
    written: `\${PI_CM_P}${SPLIT}ANTHROPIC_API_KEY}`,
    missing: [],
    runtimeEnv: { PI_CM_P: "p{env:", ANTHROPIC_API_KEY: "api-key-value" },
    claudeOutput: "p{env:ANTHROPIC_API_KEY}",
  },
  {
    title: "AVAR-03: headers } after a reference ending in {env:NAME cannot close the marker",
    field: "headers",
    raw: "${PI_CM_P}}",
    installEnv: { PI_CM_P: "{env:PI_CM_SECRET" },
    written: `\${PI_CM_P}${SPLIT}}`,
    missing: [],
    runtimeEnv: { ...SECRET_ENV, PI_CM_P: "{env:PI_CM_SECRET" },
    claudeOutput: "{env:PI_CM_SECRET}",
  },
  {
    title: "AVAR-03: url :8080 after a kept host reference gets the split token",
    field: "url",
    raw: "https://${PI_CM_HOST}:8080/mcp",
    installEnv: { PI_CM_HOST: "mcp.example.test" },
    written: `https://\${PI_CM_HOST}${SPLIT}:8080/mcp`,
    missing: [],
    runtimeEnv: { PI_CM_HOST: "mcp.example.test" },
    claudeOutput: "https://mcp.example.test:8080/mcp",
  },
  {
    title: "AVAR-03: url / after a kept host reference gets no split token",
    field: "url",
    raw: "https://${PI_CM_HOST}/mcp",
    installEnv: { PI_CM_HOST: "mcp.example.test" },
    written: "https://${PI_CM_HOST}/mcp",
    missing: [],
    runtimeEnv: { PI_CM_HOST: "mcp.example.test" },
    claudeOutput: "https://mcp.example.test/mcp",
  },
];
